export const BLOG_LIST = {
	BLOG_LIST_TITLE: "Blog Posts",
	BLOG_LIST_DRAFTS_TITLE: "Draft Posts",
	BLOG_LIST_DRAFTS_DESCRIPTION:
		"Draft posts are posts that are not published yet.",
	BLOG_LIST_TAG_TITLE: "Posts: {tag}",
	BLOG_LIST_TAG_DESCRIPTION: "All posts tagged with {tag}",
	BLOG_LIST_DESCRIPTION: "Discover our latest articles and insights",
	BLOG_LIST_EMPTY: "There are no posts here yet.",
	BLOG_LIST_LOAD_MORE: "Load more posts",
	BLOG_LIST_LOADING_MORE: "Loading more...",
	BLOG_LIST_MENU_DROPDOWN_LABEL: "Admin Options",
	BLOG_LIST_MENU_DROPDOWN_NEW_POST_BUTTON: "New Post",
	BLOG_LIST_MENU_DROPDOWN_DRAFT_POSTS: "See Drafts",
	BLOG_LIST_SEARCH_PLACEHOLDER: "Search Blog Posts...",
	BLOG_LIST_SEARCH_BUTTON: "Search Posts",
	BLOG_LIST_SEARCH_EMPTY: "No blog posts found.",
	BLOG_LIST_ERROR_TITLE: "Whoops!",
	BLOG_LIST_ERROR: "Failed to load posts",
	BLOG_TAG_PAGE_TITLE: "Posts tagged:",
	BLOG_TAG_PAGE_DESCRIPTION: "Browse all posts with this tag",
	BLOG_TAG_NOT_FOUND: "Tag not found",
	BLOG_TAG_NOT_FOUND_DESCRIPTION: "The tag you are looking for does not exist.",
};
